/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      height: {
        "navbar-custom": "10vh",
        "navbar-horizontal-line-sm-custom": "6vh",
        "navbar-horizontal-line-md-custom": "7vh",
        "navbar-horizontal-line-lg-custom": "8vh",
        "navbar-horizontal-line-xl-custom": "9vh",
        "navbar-horizontal-line-2xl-custom": "10vh",
        "navbar-logo-sm-custom": "8vh",
        "navbar-logo-md-custom": "10vh",
        "navbar-logo-lg-custom": "12vh",
        "navbar-logo-xl-custom": "14vh",
        "navbar-logo-2xl-custom": "16vh",
        "home-my-image-xl-height-custom": "100%",
        "home-my-image-md-height-custom": "80%",
        "home-my-image-sm-height-custom": "80%",
        "home-container-height-custom": "80%",
        "projects-image-sm-height-custom": "80%",
        "projects-card-height-sm-custom": "50vh",
        "projects-card-height-md-custom": "50vh",
        "projects-card-height-lg-custom": "50vh",
        "contact-input-height-custom": "30vh",
      },
      width: {
        "navbar-dummy-width": "5vw",
        "home-my-image-xl-width-custom": "30%",
        "home-my-image-md-width-custom": "50%",
        "home-my-image-sm-width-custom": "80%",
        "projects-image-sm-width-custom": "80%",
        "projects-card-width-sm-custom": "75vw",
        "projects-card-width-md-custom": "60vw",
        "projects-card-width-lg-custom": "30vw",
        "contact-input-width-sm-custom": "85vw",
        "contact-input-width-lg-custom": "25vw",
      },
      backgroundColor: {
        "darkmode-bgcolor": "#121212",
        "button-bg-custom": "#1774FF",
        "techstack-bg-light-custom": "#A7A7A7",
        "techstack-bg-dark-custom": "#646464",
      },
      colors: {
        "custom-color": "#1774FF",
      },
      margin: {
        "navbar-buttons-margin-top-custom": "220%",
        "navbar-buttons-margin-left-custom": "33vw",
        "about-margin-top-custom": "20vh",
      },
      padding: {
        "navbar-buttons-padding-top-custom": "7.5vh",
      },
      inset: {
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
        32: "8rem",
        40: "10rem",
        48: "12rem",
        56: "14rem",
        64: "16rem",
        68: "20rem",
        70: "22rem",
        auto: "auto",
        "1/2": "50%",
        "1/3": "33.333333%",
        "2/3": "66.666667%",
        "1/4": "25%",
        "3/4": "75%",
        full: "100%",
      },
      borderRadius: {
        "home-my-image-radius-custom": "10%",
      },
      boxShadow: {
        "custom-shadow": "0 0 20px rgba(23, 116, 255, 0.5)",
      },
    },
  },
  plugins: [],
};
